### ISSUE TITLE
1.15 Paper spigot error

### ISSUE THREAD

**Issue by leasoncre** [Straiker123/ServerControlReloaded#3]
**Describe the bug**
Console spammed with error messages on player join.

**Version of ServerControlReloaded**
[Thu, 9. Jan 2020 12:40:20 EST INFO] ServerControl >>> ----------------- Version -----------------
[Thu, 9. Jan 2020 12:40:20 EST INFO] ServerControl >>> Version: V7.0
[Thu, 9. Jan 2020 12:40:20 EST INFO] ServerControl >>> Server Version: 1.15.1-R0.1-SNAPSHOT

**Version of TheAPI**
Version: v3.3
Plugins using TheAPI:
- ServerControlReloaded

**Screenshots**
**Additional context**

`[12:35:15] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ServerControlReloaded v7.0
java.lang.NoClassDefFoundError: com/earth2me/essentials/Essentials
	at ServerControl.Loader.isAfk(Loader.java:136) ~[?:?]
	at Utils.TabList.replace(TabList.java:73) ~[?:?]
	at Utils.TabList.getPrefix(TabList.java:35) ~[?:?]
	at Utils.TabList.setTab(TabList.java:77) ~[?:?]
	at Events.OnPlayerJoin.PlayerJoinEvent(OnPlayerJoin.java:249) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor390.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-34]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1263) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.Essentials
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.15.1.jar:git-Paper-34]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	... 20 more`

repeated/spammed error:
`[12:35:16] [Server thread/WARN]: [ServerControlReloaded] Task #42 for ServerControlReloaded v7.0 generated an exception
java.lang.NoClassDefFoundError: com/earth2me/essentials/Essentials
	at ServerControl.Loader.isAfk(Loader.java:136) ~[?:?]
	at Utils.TabList.replace(TabList.java:73) ~[?:?]
	at Utils.TabList.setHeaderFooter(TabList.java:100) ~[?:?]
	at Utils.TabList.getHeader(TabList.java:112) ~[?:?]
	at Utils.TabList.setFooterHeader(TabList.java:138) ~[?:?]
	at Utils.Tasks$5.run(Tasks.java:144) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by Straiker123** [comment]
Do you have installed Essentials / EssentialsX plugin on your server ?

**Comment by leasoncre** [comment]
No, Though i just found EssentialsX on Paper.io, though it's not stated to officially support 1.15 yet (though i don't think much changed to the base game between those versions, and should work)
>I will add EssentialsX shortly and re-test.

**Comment by leasoncre** [comment]
error is gone with EssentialsX installed (I had EssentiallsAPIBridge on there,(w/o EssX) for bssentials, but that was also erroring >_> ... )

well, seems fixed now
still got alot to configure. #User error? though dependency not listed

**Comment by Straiker123** [comment]
BEssentials causes this error, please, send link to download BEssentials

**Comment by leasoncre** [comment]
[Bssentials Link](https://www.curseforge.com/minecraft/bukkit-plugins/bssentials)
Idk what SCR / AFK+ is.

Switched to [Luckperms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) and changed config.yml and i get a whole different issue now.

`[17:25:26] [Server thread/INFO]: [ServerControlReloaded] Enabling ServerControlReloaded v7.0
[17:25:26] [Server thread/INFO]: #SC_>>> *********************************************
[17:25:26] [Server thread/INFO]: #SC_>>> INFO: You are using version for servers version 1.15+
[17:25:26] [Server thread/INFO]: #SC_>>> INFO: Loading kits..
[17:25:26] [Server thread/INFO]: #SC_>>> Kits: Name: VIP, Cooldown: 1h : 0min, Price: $60
[17:25:26] [Server thread/INFO]: #SC_>>> Kits: Name: Default, Cooldown: 1h : 0min, Price: $25
[17:25:26] [Server thread/ERROR]: Error occurred while enabling ServerControlReloaded v7.0 (Is it up to date?)
java.lang.NullPointerException: null
	at me.Straiker123.NumbersAPI.getInt(NumbersAPI.java:104) ~[?:?]
	at me.Straiker123.TimeConventorAPI.getTimeFromString(TimeConventorAPI.java:109) ~[?:?]
	at ServerControl.Loader.APIChecker(Loader.java:389) ~[?:?]
	at ServerControl.Loader.onEnable(Loader.java:223) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-34]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-34]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-34]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[17:25:26] [Server thread/INFO]: [ServerControlReloaded] Disabling ServerControlReloaded v7.0`

[(still setting things up, but link to my plugins spreadsheet)](https://drive.google.com/file/d/1GgukmawepDjumv6RHxH8ABfU_wBWMx0y/view?usp=sharing)

PS1. Why does the plugin overwrite almost all of the config files if it finds a single syntax error? This is rather annoying. #backups.
PS2. Need a list of Syntax-EXACT Timezones. I tried to change it a few times and it just errored out. tried changing it back and it still errors out. The link in file does not list the exact syntaxing and valid values that are required. ---umm.. for w/e reason it initially loaded with "Europe/Prague", but is now loading with "Eastern Standard Time" (which is correct) w/e..
PS3. how to disable kits entirely?

Thank you.

-Config file attached.
[Config.txt](https://github.com/Straiker123/ServerControlReloaded/files/4050034/Config.txt)

**Comment by leasoncre** [comment]
Started up a fresh server/instance to do some testing:
-Everything loads up fine with defaults. (added only EssentialsX+Chat, Luckperms, TheAPI,Vault)
-restarted twice, (once to generate files, 2nd to load from generated config files)
Initial server join generated this: `[10:36:07] [Server thread/WARN]: String 'OnJoin.Web' isn't exist in Tranlations.yml, please report this bug on https://github.com/Straiker123/ServerControlReloaded`
-Added PlaceholderAPI (used by another plugin for something, though SCR uses it for??) and That throws an error on startup.

-> Went back to look at the config.yml on main server. changed a bunch of things. stare'd at error for a while (stack-trace): 
opened Kits.yml and found an out-of-place number at the beginning of a line where it shouldn't have been. removed it and the YAML parser error is gone now. Problem Fixed. ->Now if the error had read "YAML Parser Error at x line, y col, in file filename.yml" to begin with, i probably would have understood the issue immediately. >< .... since it said NumbersAPI, i thought it was some other issue. (idk what it does)

PS. I prefer to directly edit the YAML configs, but when the server stops, the plugin overwrites any changes i made while it was running. Consider adding a 'detect changes to config files' ability.
PPS. What does the AntiAD: section of the config do?
Thank you. (Close ticket on next reply)
